CREATE OR REPLACE TRIGGER trg_audita_clientes
AFTER INSERT OR UPDATE OR DELETE ON clientes
FOR EACH ROW
BEGIN
    INSERT INTO audita_clientes(
        user_name,
        CODIGO_CLIENTE_OLD, NOMBRE_CLIENTE_OLD, NOMBRE_CONTACTO_OLD, APELLIDO_CONTACTO_OLD, 
        TELEFONO_OLD, FAX_OLD, LINEA_DIRECCION1_OLD, LINEA_DIRECCION2_OLD, CIUDAD_OLD, 
        REGION_OLD, PAIS_OLD, CODIGOPOSTAL_OLD, CODIGO_EMPLEADO_REP_VENTAS_OLD, LIMITECREDITO_OLD,
        CODIGO_CLIENTE_NEW, NOMBRE_CLIENTE_NEW, NOMBRE_CONTACTO_NEW, APELLIDO_CONTACTO_NEW, 
        TELEFONO_NEW, FAX_NEW, LINEA_DIRECCION1_NEW, LINEA_DIRECCION2_NEW, CIUDAD_NEW, 
        REGION_NEW, PAIS_NEW, CODIGOPOSTAL_NEW, CODIGO_EMPLEADO_REP_VENTAS_NEW, LIMITECREDITO_NEW,
        fecha
    )
    VALUES (
        USER,
        :OLD.CODIGOCLIENTE, :OLD.NOMBRECLIENTE, :OLD.NOMBRECONTACTO, :OLD.APELLIDOCONTACTO,
        :OLD.TELEFONO, :OLD.FAX, :OLD.LINEADIRECCION1, :OLD.LINEADIRECCION2, :OLD.CIUDAD,
        :OLD.REGION, :OLD.PAIS, :OLD.CODIGOPOSTAL, :OLD.CODIGOEMPLEADOREPVENTAS, :OLD.LIMITECREDITO,
        :NEW.CODIGOCLIENTE, :NEW.NOMBRECLIENTE, :NEW.NOMBRECONTACTO, :NEW.APELLIDOCONTACTO,
        :NEW.TELEFONO, :NEW.FAX, :NEW.LINEADIRECCION1, :NEW.LINEADIRECCION2, :NEW.CIUDAD,
        :NEW.REGION, :NEW.PAIS, :NEW.CODIGOPOSTAL, :NEW.CODIGOEMPLEADOREPVENTAS, :NEW.LIMITECREDITO,
        CURRENT_TIMESTAMP
    );
END;
/


CREATE OR REPLACE TRIGGER trg_audita_pedidos
AFTER INSERT OR UPDATE OR DELETE ON pedidos
FOR EACH ROW
BEGIN
    INSERT INTO audita_pedidos (
        user_name,
        CODIGOPEDIDO_OLD, FECHAPEDIDO_OLD, FECHAESPERADA_OLD, FECHAENTREGA_OLD,
        ESTADO_OLD, COMENTARIOS_OLD, CODIGOCLIENTE_OLD,
        CODIGOPEDIDO_NEW, FECHAPEDIDO_NEW, FECHAESPERADA_NEW, FECHAENTREGA_NEW,
        ESTADO_NEW, COMENTARIOS_NEW, CODIGOCLIENTE_NEW,
        fecha
    )
    VALUES (
        USER,
        :OLD.CODIGOPEDIDO, :OLD.FECHAPEDIDO, :OLD.FECHAESPERADA, :OLD.FECHAENTREGA,
        :OLD.ESTADO, :OLD.COMENTARIOS, :OLD.CODIGOCLIENTE,
        :NEW.CODIGOPEDIDO, :NEW.FECHAPEDIDO, :NEW.FECHAESPERADA, :NEW.FECHAENTREGA,
        :NEW.ESTADO, :NEW.COMENTARIOS, :NEW.CODIGOCLIENTE,
        CURRENT_TIMESTAMP
    );
END;
/

